### ISSUE TITLE
RDRAM latency deep dive?

### ISSUE THREAD

**Issue by cheater** [RobertPeip/Mister64#18]
Hi,
I've been following your project from the sidelines for a while. It was recently reported that you've tried every possibility for handling the RDRAM latency and some games will unfortunately end up with some minor bugs. It's a wonder you got this far, and as a fellow dev I would be curious to hear what you have tried. I think it would be very informative and I would love to read a deep dive about this, or like a post mortem or a presentation or a stream. I think I could learn a bunch from that. Or maybe you can just post some thoughts here.

Thanks!

**Comment by RobertPeip** [comment]
You can read the patreon article about the DDR3, it's public: https://www.patreon.com/posts/82932537

There is not much more to say: I assumed the rare case of random high latency(>100 cycles) could be solved, but in some cases it's just too slow for the single access and cannot be solved by speeding up future accesses.
Solution is to use a dedicated DDR3/4 for the RDRAM and the issue is gone.
